<?php
/*
 * Copyright (c) 2013, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

////////////////////////////////////////////////////////
// print breadcrumb path

$base  = 'index.php?page=mediapool_structure&amp;cat_id=';
$path  = '<li> : <a href="'.$this->appendQueryString($base.'0').'">'.ht('start').'</a></li>';
$catID = sly_request('cat_id', 'int');
$cat   = sly_Util_MediaCategory::findById($catID);

if ($cat === null) {
	$categories = sly_Util_MediaCategory::getRootCategories();
	$catID      = 0;
}
else {
	$categories = $cat->getChildren();
	$parents    = $cat->getParentTree();

	foreach ($parents as $parent) {
		$path .= '<li> : <a href="'.$this->appendQueryString($base.$parent->getId()).'">'.sly_html($parent->getName()).'</a></li>';
	}

	$path .= '<li> : <a href="'.$this->appendQueryString($base.$catID).'">'.sly_html($cat->getName()).'</a></li>';
}

?>
<div class="sly-navi-path">
	<ul>
		<li><?php echo t('path') ?></li>
		<?php echo $path ?>
	</ul>
</div>
<?php

////////////////////////////////////////////////////////
// info and error messages

$this->render('mediapool/notices.phtml', array(), false);

////////////////////////////////////////////////////////
// start form if needed

$editID = sly_request('edit_id', 'int');

if ($this->action == 'add' || $this->action == 'edit') {
	$addMode = $this->action == 'add';
	$form    = new sly_Form('index.php', '');

	$form->addHiddenValue('page', 'mediapool_structure');
	$form->addHiddenValue('cat_id', $catID);
	$form->addHiddenValue('func', $this->action);

	if ($editID) {
		$form->addHiddenValue('edit_id', $editID);
	}

	$this->appendParamsToForm($form);
	$form->setSubmitButton(null);
	$form->setResetButton(null);

	?>
	<form action="index.php" method="post">
	<?php

	print $form->render(true);
}

$rawBase = 'index.php?page=mediapool_structure&cat_id=';
$table   = new sly_Table('sly-mediapool-structure');

$table->addColumn(sly_Table_Column::sprite('mediacat-add', $this->appendQueryString($rawBase.$catID.'&func=add', '&'), t('add_category'), 'sly-col-icon'));
$table->addColumn(sly_Table_Column::factory(t('category_name'), 'sly-col-name'));
$table->addColumn(sly_Table_Column::factory(t('function'), 'sly-col-func'));

$table->setIsEmpty(empty($categories) && $this->action !== 'add');
$table->setEmptyNotice(t('no_categories_yet'));
$table->openBuffer();

if ($this->action === 'add') {
	?>
	<tr class="sly-active">
		<td class="sly-col-icon sly-icon"><?php echo sly_Util_HTML::getSpriteLink('', t('add_category'), 'mediacat') ?></td>
		<td class="sly-col-name sly-has-input"><div><input class="sly-form-text" type="text" size="10" id="sly-form-field-name" name="catname" value="" autofocus="autofocus" required="required" placeholder="<?php echo ht('category_name') ?>" /></div></td>
		<td class="sly-col-func sly-has-input"><div><input type="submit" class="sly-form-submit" value="<?php echo t('add') ?>" /></div></td>
	</tr>
	<?php
}

foreach ($categories as $cat) {
	$id = $cat->getId();

	if ($this->action == 'edit' && $editID == $id) {
		?>
		<tr class="sly-active">
			<td class="sly-col-icon sly-icon"><?php echo sly_Util_HTML::getSpriteLink('', $cat->getName(), 'mediacat') ?></td>
			<td class="sly-col-name sly-has-input"><div><input class="sly-form-text" type="text" id="sly-form-field-name" name="catname" value="<?php echo sly_html($cat->getName()) ?>" autofocus="autofocus" required="required" placeholder="<?php echo ht('category_name') ?>" /></div></td>
			<td class="sly-col-func sly-has-input" colspan="2"><div><input type="submit" class="sly-form-submit" value="<?php echo t('save') ?>" /></div></td>
		</tr>
		<?php
	}
	else {
		?>
		<tr>
			<td class="sly-col-icon sly-icon"><?php echo sly_Util_HTML::getSpriteLink($this->appendQueryString($rawBase.$catID.'&func=edit&edit_id='.$id, '&'), $cat->getName(), 'mediacat') ?></td>
			<td class="sly-col-name"><a href="<?php echo $this->appendQueryString($base.$id) ?>"><?php echo sly_html($cat->getName()) ?></a></td>
			<td class="sly-col-func">
				<a href="<?php echo $this->appendQueryString($base.$catID.'&amp;func=edit&amp;edit_id='.$id) ?>"><?php echo t('change')?></a>
				<a href="<?php echo $this->appendQueryString($base.$catID.'&amp;func=delete&amp;edit_id='.$id) ?>" class="sly-action sly-delete"><?php echo t('delete') ?></a>
			</td>
		</tr>
		<?php
	}
}

$table->closeBuffer();
print $table->render();

if ($this->action === 'add' || $this->action === 'edit') {
	print '</form>';
}
