language: php

php:
   - 5.2
   - 5.3
   - 5.4

install:
   - chmod +x contrib/setup-travis.sh
   - ./contrib/setup-travis.sh

script:
   - phpunit --configuration sally/tests/full.xml

notifications:
   email:
      recipients:
         - travis-ci-monitor@sallycms.de
