language: php

php:
#   - 5.2  # disabled until we can install our dependencies without Composer
   - 5.3
   - 5.4

install:
   - 'wget -q http://getcomposer.org/composer.phar'
   - 'php composer.phar install --dev'
   - 'mysql -e "CREATE DATABASE sally_test"'
   - 'mysql --database=sally_test < sally/core/install/mysql.sql'
   - 'mysql --database=sally_test -e "INSERT INTO sly_user (id,name,description,login,psw,status,rights,lasttrydate,timezone,createdate,updatedate,createuser,updateuser) VALUES (1, ''Admin'', '''', ''admin'', ''c5e4335577bb89540b15e2f5251e8bc02ced5b32'', 1, ''#admin[]#'', 1317608132, ''Europe/Berlin'', 1302655028, 1311293111, ''setup'', ''admin'')"'

script:
   - phpunit --strict --bootstrap sally/tests/bootstrap.php sally/tests/tests
